# Generated by Django 4.2.21 on 2025-05-24 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=100, verbose_name='작성자')),
                ('description', models.TextField(verbose_name='수정 설명')),
                ('patch_file', models.FileField(upload_to='patches/', verbose_name='패치 zip 파일')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='등록일')),
            ],
        ),
    ]
