# Generated by Django 4.2.21 on 2025-05-24 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patchlog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='patch',
            name='zip_name',
            field=models.CharField(default='default', max_length=50, verbose_name='최종 zip 이름'),
            preserve_default=False,
        ),
    ]
